cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: AKIA4MFLODBGALHSRHXD
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/850763061324/sqs-queue-demo-bharathi
  server:
    port: 9091